### ISSUE TITLE
CF-release

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry/diego-cf-compatibility#1]
Hi,

Is pretty difficult to get the CF-release version with the commit sha, It will a lot more convenient if we can have v201 etc ..

**Comment by luan** [comment]
The entries on the compatibility matrix come from development and release-candidate builds, there is no final bosh release version for it. We have a story (https://www.pivotaltracker.com/story/show/93811624) to add more documentation regarding this matrix. We'll also talk about how we can improve it based on that (maybe by adding final releases to the mix).
Thanks for the feedback!

Luan,
CF Diego Team

**Comment by shinji62** [comment]
Nice, because people rely on final version never on the dev / commit based one.
