### ISSUE TITLE
Fix erroneous quoting in compatibility-v7.csv

### ISSUE THREAD

**Issue by emalm** [cloudfoundry/diego-cf-compatibility#6]
[Line 19](https://github.com/cloudfoundry/diego-cf-compatibility/blob/master/compatibility-v7.csv#L19) in compatibility-v7.csv introduces some quotes that are not escaped properly, so GitHub does not render the CSV file as a formatted table. This likely requires logic in the [rc](https://runtime.ci.cf-app.com/teams/main/pipelines/cf-release/jobs/rc) CI job to change.

Thanks,
Eric

**Comment by dsabeti** [comment]
@ematpl I've edited the compatibility matrix not to have the quotes, and I've also fixed our script to strip them if they're present: https://github.com/cloudfoundry/runtime-ci/commit/9ce3f7e5c427a8acfcb4c3228b4118c6fce33212

Let me know if you see this problem again.

**Comment by emalm** [comment]
Awesome, thanks, @dsabeti !

Best,
Eric
